schemaVersion: 1
enabledWorkflows:
  - session-management
  - simulator
  - ui-automation
  - debugging
  - logging
  - device
sessionDefaults:
  simulatorName: Falcon E2E
  simulatorId: 50E9E48E-D7F7-4338-9873-3EB801137EE7
  simulatorPlatform: iOS Simulator
